-- =========================
-- TABLES - ORACLE VERSION
-- =========================

CREATE TABLE categories (
    category_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(100) NOT NULL,
    description   VARCHAR2(500)
);

CREATE TABLE products (
    product_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(200) NOT NULL,
    category_id   NUMBER,
    price         NUMBER(10,2) NOT NULL,
    stock         NUMBER DEFAULT 100,
    CONSTRAINT fk_products_category 
        FOREIGN KEY (category_id) 
        REFERENCES categories(category_id)
);

CREATE TABLE customers (
    customer_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR2(150) NOT NULL,
    email              VARCHAR2(100) UNIQUE,
    registration_date  DATE DEFAULT SYSDATE
);

CREATE TABLE orders (
    order_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   NUMBER,
    order_date    DATE DEFAULT SYSDATE,
    status        VARCHAR2(20) DEFAULT 'completed',
    total_amount  NUMBER(12,2),

    CONSTRAINT fk_orders_customer 
        FOREIGN KEY (customer_id) 
        REFERENCES customers(customer_id),

    CONSTRAINT chk_orders_status 
        CHECK (status IN ('pending','completed','cancelled'))
);

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER,
    product_id    NUMBER,
    quantity      NUMBER NOT NULL,
    unit_price    NUMBER(10,2) NOT NULL,

    CONSTRAINT fk_oi_order 
        FOREIGN KEY (order_id) 
        REFERENCES orders(order_id),

    CONSTRAINT fk_oi_product 
        FOREIGN KEY (product_id) 
        REFERENCES products(product_id)
);

CREATE TABLE payments (
    payment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     NUMBER,
    payment_date DATE DEFAULT SYSDATE,
    amount       NUMBER(12,2) NOT NULL,
    method       VARCHAR2(50) DEFAULT 'card',

    CONSTRAINT fk_payments_order 
        FOREIGN KEY (order_id) 
        REFERENCES orders(order_id)
);

CREATE TABLE reviews (
    review_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  NUMBER,
    customer_id NUMBER,
    rating      NUMBER,
    review_comment     VARCHAR2(1000),
    review_date DATE DEFAULT SYSDATE,

    CONSTRAINT fk_reviews_product 
        FOREIGN KEY (product_id) 
        REFERENCES products(product_id),

    CONSTRAINT fk_reviews_customer 
        FOREIGN KEY (customer_id) 
        REFERENCES customers(customer_id),

    CONSTRAINT chk_reviews_rating 
        CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE inventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   NUMBER,
    quantity     NUMBER NOT NULL,
    last_updated DATE DEFAULT SYSDATE,

    CONSTRAINT fk_inventory_product 
        FOREIGN KEY (product_id) 
        REFERENCES products(product_id)
);